Gift Entry: Only render fields with valid mappings
SalesforceFoundation/NPSP pull request #5860
Opened 2020-09-18 17:38 UTC by bdvorachek

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

2020-09-18 20:33 UTC, bdvorachek commented on src/classes/BDI_MappingServiceAdvanced.cls
> +            if(targetObjectMapping != null) {
the `if` block is the main change here - if the targetObjectMapping does not exist we need to skip it, because the target SObject was likely deleted.

2020-09-21 17:03 UTC, psadie-sfdo requested changes
Dropping in the feedback I had that was on Daniel's PR now, but still running through!

2020-09-22 14:50 UTC, bdvorachek commented on src/classes/BGE_BatchGiftEntry_UTIL.cls
> +                        SObjectField field = DataImport__c.SObjectType.getDescribe()
The `Schema.SObjectField field` here also gets used a bit further down the road in `UTIL_Describe.getReferenceObjectNameField(field)`. We don't have a way to get a `Schema.SObjectField` from any method in UTIL_Describe - so there's a bit of a refactor needed to get rid of this describe call. Overloading `getReferenceObjectNameField` is one possible solution here.

2020-09-22 22:35 UTC, bdvorachek commented on src/classes/GE_FormRendererService.cls
> +                        if (fieldMapping != null && element != null) {
This is a typo from debugging that snuck along on one of the pushes, good catch! Removed.

2020-09-22 22:36 UTC, bdvorachek commented on src/lwc/geFormSection/geFormSection.js
> +        if (!isUndefined(this.section)) {
Good for readability, that change is in.

2020-09-22 22:41 UTC, bdvorachek commented on src/classes/FORM_PermissionValidator.cls
> +                                if (!isValid(sourceObjDevName, accessLevels)) {
I split these 4 blocks into two private functions. `Map<String, Set<String>> permissionErrorsBySObject` was upgraded to being a member variable, and all instances of passing `Set<String> accessLevels` to functions are gone in favor of using the member variable.

2020-09-22 23:06 UTC, voduyemi requested changes
Looks good! @bdvorachek Just had a comment about the `isDescribable` field in the `BDI_ObjectMapping` class.

2020-09-23 00:33 UTC, bdvorachek commented on src/classes/BDI_ObjectMapping.cls
> +    @AuraEnabled public Boolean isDescribable;
Nope, this is not currently in use anywhere. Removed.

2020-09-23 16:58 UTC, ptewson-sfdo approved these changes
This looks great!!

2020-09-23 17:00 UTC, ptewson-sfdo commented on src/package.xml
> +        <members>geHelpers</members>
This is causing an issue when I attempt to deploy!

2020-09-25 14:56 UTC, psadie-sfdo approved these changes
Looks good!
_I have non-blocking comments below around style, but I wouldn't hold this PR up for those._

2020-09-25 15:37 UTC, voduyemi approved these changes
Looks good!

2020-09-25 17:02 UTC, bdvorachek commented on src/classes/GE_GiftEntryController.cls
> +                    (updateGift);
updated.

2020-09-25 20:31 UTC, merged