Add Preflight Checks
SalesforceFoundation/NPSP pull request #6021
Opened 2020-11-12 20:02 UTC by davidmreed

This PR is dependent on the merge and release of [this CumulusCI PR](https://github.com/SFDO-Tooling/CumulusCI/pull/2162).

We now preflight-check before installing NPSP:

- Chatter must be turned on for all install plans
- Advanced Currency Management must be turned off for all plans
- NPSP must be installed to run the Reports & Dashboards plan
- NPSP must _not_ be installed to run the Trailhead installer.

Installer for testing (*VPN required*): (to be republished)

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

2020-12-04 20:02 UTC, melissabarber requested changes
Added the same suggestion a few times and added a comment about why I recommended that change. If it seems important to keep that sentence, maybe update it to, "See the Power of Us Hub for more information."

2020-12-04 20:02 UTC, melissabarber commented on cumulusci.yml
> +              message: "Advanced Currency Management must be disabled to install Nonprofit Success Pack, but can be enabled after installation. See the Power of Us Hub for assistance."
```suggestion
              message: "Advanced Currency Management must be disabled to install Nonprofit Success Pack, but can be enabled after installation."
```

2020-12-04 20:02 UTC, melissabarber commented on metadeploy/labels_en.json
> +            "message": "Advanced Currency Management must be disabled to install Nonprofit Success Pack, but can be enabled after installation. See the Power of Us Hub for assistance.",
```suggestion
            "message": "Advanced Currency Management must be disabled to install Nonprofit Success Pack, but can be enabled after installation.",
```

2020-12-07 21:29 UTC, davidmreed commented on cumulusci.yml
> +              message: "Advanced Currency Management must be disabled to install Nonprofit Success Pack, but can be enabled after installation. See the Power of Us Hub for assistance."
I don't think it's important. I'll adopt all of your suggestions.

2020-12-07 21:56 UTC, melissabarber approved these changes
Messaging looks great to me!

2020-12-07 21:58 UTC, davidmreed commented on cumulusci.yml
> +            - when: "not 'npsp' in org_config.installed_packages"
```suggestion
            - when: "'npsp' in org_config.installed_packages"
```

2020-12-07 22:00 UTC, davidmreed commented on cumulusci.yml
> +            - when: "not 'npsp' in org_config.installed_packages"
```suggestion
            - when: "'npsp' not in org_config.installed_packages"
```

2020-12-07 22:02 UTC, davidmreed commented on cumulusci.yml
> +            - when: "not tasks.check_advanced_currency_management()"
```suggestion
            - when: "tasks.check_advanced_currency_management()"
```

2020-12-07 22:02 UTC, davidmreed commented on cumulusci.yml
> +            - when: "not tasks.check_advanced_currency_management()"
```suggestion
            - when: "tasks.check_advanced_currency_management()"
```

2021-01-08 16:02 UTC, bdvorachek approved these changes

2021-01-08 16:45 UTC, merged