[GS][W-8515435] Add 'WITH SECURITY_ENFORCED' to SOQL
SalesforceFoundation/NPSP pull request #6080
Opened 2020-11-30 19:53 UTC by fparodi-salesforce

# Critical Changes

# Changes
 Add 'WITH SECURITY_ENFORCED' to SOQL
# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

2020-11-30 19:54 UTC, fparodi-salesforce commented
[W-8515435](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008kQ1vIAE/view)

2020-11-30 21:28 UTC, force2b requested changes

2020-11-30 21:28 UTC, force2b commented on src/classes/GS_NonprofitTrialOrgService.cls
> +            WITH SECURITY_ENFORCED
This clause should only be used on standard and custom objects, not system objects.

2020-11-30 21:28 UTC, force2b commented on src/classes/GS_NonprofitTrialOrgService.cls
> +            SELECT Body FROM StaticResource
This clause should only be used on standard and custom objects, not system objects.

2020-12-01 13:58 UTC, force2b requested changes
There's another query on line 69 that should be updated.

2020-12-02 00:47 UTC, force2b approved these changes
This looks good. 

I want to make an important note now that I'm aware that there will be a similar page for End Users. The concept with the Admin pages was that only a "true" admin would ever use these pages so the additional query/dml security makes sense. However, when it comes to the End User page, I think that we may want to reconsider the use of `WITH SECURITY_ENFORCED` for that pages controller. The premise is that we'd want _any_ end user to be able to access the new page even if an Admin hasn't explicitly granted the User crud and fls to the CMDT and `GetStartedCompletionChecklistState__c` objects - which will be especially true in smaller P10 orgs where there might not even be admin present. My preference would be that for _that_ specific EndUser page the controller uses `Without Sharing` on the class and that queries/dml are done without reference to `With Security_Enforced`' - if everyone agrees.
cc @dcaballeroSf @smarovich @ameyersalesforce

2020-12-02 14:51 UTC, merged

2020-12-02 20:23 UTC, ameyersalesforce commented
> This looks good.
> 
> I want to make an important note now that I'm aware that there will be a similar page for End Users. The concept with the Admin pages was that only a "true" admin would ever use these pages so the additional query/dml security makes sense. However, when it comes to the End User page, I think that we may want to reconsider the use of `WITH SECURITY_ENFORCED` for that pages controller. The premise is that we'd want _any_ end user to be able to access the new page even if an Admin hasn't explicitly granted the User crud and fls to the CMDT and `GetStartedCompletionChecklistState__c` objects - which will be especially true in smaller P10 orgs where there might not even be admin present. My preference would be that for _that_ specific EndUser page the controller uses `Without Sharing` on the class and that queries/dml are done without reference to `With Security_Enforced`' - if everyone agrees.
> cc @dcaballeroSf @smarovich @ameyersalesforce

I mentioned this in Slack too, but I think we should use Without Sharing for both the admin and end user page (or whatever ensures that anyone can access both pages). For the admin page, our target audience are admins who are JUST starting - they have no idea about permissions and we don't want to present additional hurdles to them - we want to make it as easy as possible. Plus, there isn't any content on the page that is protected or high risk or anything like that. 

For end users, we want end users to be able to access it, so - once again, I think we should NOT enforce permissions on these pages.

2020-12-02 20:49 UTC, force2b commented
Thanks @ameyersalesforce. @dcaballeroSf To make these pages truly visible to anyone, we'll also need to change the page controllers to use `without sharing` (alternatively move queries into an inner class that is defined as `without sharing`).