Feature/dcaballero/gs labels change
SalesforceFoundation/NPSP pull request #6111
Opened 2020-12-10 15:33 UTC by dcaballeroSf

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

2020-12-10 15:34 UTC, dcaballeroSf commented
[WI-8532798](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008kiuRIAQ/view)

2020-12-11 20:43 UTC, force2b requested changes

2020-12-11 20:43 UTC, force2b commented on src/labels/CustomLabels.labels
> +        <value>Learn how to customize NPSP reports &amp; Dashboard in Trailhead</value>
```suggestion
        <value>Learn how to customize NPSP reports &amp; Dashboards in Trailhead</value>
```

2020-12-11 20:43 UTC, force2b commented on src/labels/CustomLabels.labels
> +        <categories>tart Managing Programs</categories>
```suggestion
        <categories>Start Managing Programs</categories>
```

2020-12-11 20:43 UTC, force2b commented on src/labels/CustomLabels.labels
> +        <categories>Start Engaging Constituents</categories>
Why did the category change here and below? That should be the same for all GetStarted labels

2020-12-11 20:43 UTC, force2b commented on src/labels/CustomLabels.labels
> +        <categories>Get Started on NPSP</categories>
```suggestion
        <categories>Get Started Page</categories>
```

2020-12-14 16:58 UTC, force2b approved these changes

2020-12-16 17:36 UTC, merged