[GS End User] [W-8545389] - Checklist Section 2 (Create Constituent Records)
SalesforceFoundation/NPSP pull request #6173
Opened 2021-01-12 22:03 UTC by e-ferrando

# Critical Changes

# Changes
Create custom metadata and labels for Create Constituent Records section in Get Started page
# Issues Closed

# Community Ideas Delivered

# New Metadata
Custom metadata
        GetStartedChecklistItem.Connect_a_Contact_to_an_Organization
        GetStartedChecklistItem.Connect_Two_Contacts_with_Relationships
        GetStartedChecklistItem.Create_Contacts_and_Household_Accounts
        GetStartedChecklistSection.CreateConstituentRecords_NPSP

Custom labels
      gseuChecklistCreateConstituentRecordsTitle
      gseuChecklistCreateConstituentRecordsDesc
      
      gseuChecklistItemCreateContactAndAccountTitle
      gseuChecklistItemCreateContactAndAccountDesc
      gseuChecklistItemCreateContactAndAccountLink
      gseuChecklistItemCreateContactAndAccountBlueButton
      
      gseuChecklistItemConnectContactsRelationshipsTitle
      gseuChecklistItemConnectContactsRelationshipsDesc
      gseuChecklistItemConnectContactsRelationshipsLink
      gseuChecklistItemConnectContactsRelationshipsBlueButton
      
      gseuChecklistItemConnectContactOrganizationTitle
      gseuChecklistItemConnectContactOrganizationDesc
      gseuChecklistItemConnectContactOrganizationLink
      gseuChecklistItemConnectContactOrganizationBlueButton

# Deleted Metadata

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <shortDescription>Title for Create Constituent Records section in Gest Started</shortDescription>
Please fix small typo in "Get".

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <shortDescription>Blue button text for Connect Contacts to Organization checklist item</shortDescription>
I don't think we want to use colors for accessibility reasons. I would just say: Button label for Connect Contacts to Organization checklist item

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <shortDescription>Title for Connect Contact to Organization checklist item in Get Started page</shortDescription>
I think you can remove the word "page" from the end of the description to keep it consistent with others.

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <shortDescription>Blue button text for Connect Two Contacts with Relationships checklist item</shortDescription>
Again, I would avoid the use of the color for accessibility reasons. Please use: Button text for Connect Two Contacts with Relationships checklist item

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <shortDescription>Blue button text for Create Contacts and Account checklist item in Get Started</shortDescription>
Please use: Button text for Create Contacts and Account checklist item in Get Started

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <shortDescription>Description for Create Contacts and Account checklist item in Get Started page</shortDescription>
Please remove the word "page". I would also remove the word "Create" to make this consistent with other short descs for the section.

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <value>Learn more about Contact and Accounts in Trailhead</value>
Contacts should be plural.

2021-01-12 22:42 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <shortDescription>Title for Create Contacts and Account checkbox item in Get Started page</shortDescription>
Please change to: Title for Contacts and Accounts checklist item in Get Started.

2021-01-12 22:53 UTC, force2b requested changes

2021-01-12 22:53 UTC, force2b commented on src/labels/CustomLabels.labels
> +    <labels>
Can you place these in the same labels file alphabetically? There are other labels that start with `gseu` so these new labels should fit in with them.

2021-01-13 15:28 UTC, force2b commented
@e-ferrando There are two issues with these branch names that I didn't notice before: 

1. All branches need to start with `feature/`. Neither this branch or the one it merges into start with `feature/`. You'll be unable to merge branches into master unless they start with feature. Even this branch is questionable because none of the standard builds have run. This issue will have to be fixed in order to continue with any of this work.
1. This branch merges into another child branch. Child branches are defined as a branch with that contains a double underscrore. So, in this case `adoption__W-8545389-Checklist-Section-2--Create-Constituent-Records` (which is technically a child of `adoption`) is set to merge into `adoption__W-8528035-Checklist-Section-1-(Welcome)` which is also a child branch of `adoption`. MetaCI (our CI/CD) built system only supports a single level of parent child branches. In other words, this branch can merge into `feature/adoption' (which would be the correct branch name), but merging one child branch into another child branch will create a ton of merge conflict issues. You happen to be escaping these only because the branches are missing the `feature/` prefix.

My recommendation is to get this branch tested and then fix all of the branch names on all of the PR's you're working with making sure the PR is merging into a parent branch or master, but never into another child branch.
CC @dcaballeroSf

2021-01-13 19:24 UTC, smarovich commented on src/labels/CustomLabels.labels
> +        <value>Learn more about Contact and Accounts in Trailhead</value>
Contacts should be plural. Please change this to: Learn more about Contacts and Accounts in Trailhead

2021-01-15 22:19 UTC, merged

2021-01-19 18:18 UTC, smarovich reviewed
Labels look good!