Ensure proper permissions when accessing the "Refresh Opportunity Names" page in NPSP Settings
SalesforceFoundation/NPSP pull request #6190
Opened 2021-01-19 22:09 UTC by force2b

# Critical Changes

- In order to use the "Refresh Opportunity Names" page in NPSP Settings, the User must have Update access to the Opportunity object as well as Read access to both the Account and Contact objects.

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

2021-01-19 22:10 UTC, force2b commented
[W-8428988](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008iqpvIAA/view)

2021-01-20 19:30 UTC, andrewyu-salesforce approved these changes
@force2b everything looks great.

2021-01-20 22:12 UTC, npsp-reedestockton requested changes
Looks great!  Just a couple of small formatting comments.

2021-01-20 22:19 UTC, force2b commented on src/classes/STG_PanelOppNamingBatch_CTRL.cls
> +        if (String.isBlank(namespace)) return 'c';
Definitely. Good catch. I'll fix the class I copied it from as well.

2021-01-20 22:24 UTC, npsp-reedestockton approved these changes
Nice!  Thanks!

2021-01-26 17:13 UTC, merged