Gift Entry - Fixed Get Template Record keyword + Opportunity Page element finding
SalesforceFoundation/NPSP pull request #6341
Opened 2021-03-30 18:34 UTC by schlossmj

# Critical Changes

- Fixes an issue where the keyword to delete form templates was not accounting for namespacing, and thus templates were not being deleted during cleanup. Fixed this to work in both namespaced and non-namespaced orgs.
- Fixes an issue where the 'Current Page Should Be' keyword was not finding page button elements on the Opportunity Details page.

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

2021-03-30 18:58 UTC, deepmalamehta requested changes

2021-03-30 18:58 UTC, deepmalamehta commented on robot/Cumulus/resources/OpportunityPageObject.py
> +        self.selenium.wait_until_page_contains("Delete")
Seems like 2 different locators to me. Originally it was trying to find Manage HH and now Delete. Please make sure if this keyword is being used anywhere else and solving the same issue.

2021-03-30 19:45 UTC, deepmalamehta commented on robot/Cumulus/resources/OpportunityPageObject.py
> +        self.selenium.wait_until_page_contains("Delete")
Great. Look good then.

2021-03-30 19:45 UTC, deepmalamehta approved these changes

2021-03-30 21:18 UTC, rjanjanam approved these changes

2021-04-05 20:49 UTC, deepmalamehta approved these changes

2021-04-05 22:36 UTC, skristem approved these changes
looks good

2021-04-06 13:27 UTC, merged