Contact Merge Button Error When Clicked Twice
SalesforceFoundation/NPSP pull request #6384
Opened 2021-04-28 18:51 UTC by dfuller114

# Critical Changes

# Changes

# Issues Closed
Fixes #5779 

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2021-04-28 19:18 UTC, npsp-reedestockton requested changes
Looks great.  One minor formatting change request.

2021-04-28 19:18 UTC, npsp-reedestockton commented on src/pages/CON_ContactMerge.page
> +                                                            {!$Label.conMergeSelectContact} <apex:outputText
New line for <apex:outputText...?

2021-04-28 19:56 UTC, lparrott approved these changes
Works great, nicely done!

2021-04-28 20:40 UTC, dfuller114 commented on src/pages/CON_ContactMerge.page
> +                                                            {!$Label.conMergeSelectContact} <apex:outputText
updated!

2021-04-28 21:04 UTC, npsp-reedestockton approved these changes

2021-04-28 21:04 UTC, npsp-reedestockton commented
Nice!!!

2021-05-04 00:19 UTC, rponti-sforg commented
QE testing is complete for this PR and subsequent WI.  Tests have passed based on WI Description, AC(s), PR comments, and design document

For further testing details, see:
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008UcphIAC/view
https://salesforce.quip.com/drZ9AvafFjp7

Proceeding with merge of PR.  Will set WI status to 'Pending Release' and then 'Closed' once post-merge builds pass.

2021-05-04 00:19 UTC, merged