"See Duplicate Contact" option on NPSP Contact Merge issue fixed
SalesforceFoundation/NPSP pull request #6571
Opened 2021-07-26 22:13 UTC by npsp-reedestockton

# Critical Changes

# Changes
The Contact Merge > See Duplicate Contacts page has the following changes:
- Duplicate Record Sets that include a Lead Duplicate Record Item no longer cause an error.
- The "Record Count" column has been replaced with a "Contact Count" column.
- Duplicate Record Sets that include one or more Leads and only one Contact are not displayed.
- Duplicate Record Sets that include one or more Leads and two or more Contacts are displayed.
- When the "Pick" button is pressed, only Contact records are displayed as merge candidates.

# Issues Closed
Fixes #5568 

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2021-07-26 22:15 UTC, npsp-reedestockton commented
Tracks [W-7693961](https://gus.lightning.force.com/a07B0000008S1AGIA0)

2021-07-26 22:16 UTC, npsp-reedestockton commented
@sam-knox Would appreciate your comments on PR description and title.  Also, there is a new label.  Replacing "Record Count" column with "Contact Count".  Not sure how creative you can be with that label change, but give it your best shot!

2021-07-27 12:59 UTC, force2b commented on force-app/main/default/classes/CON_ContactMerge_CTRL.cls
> +                    firstContactOfDRS.put(dri.DuplicateRecordSetId, con);
Is it worth abstracting out the contents of the for loop into its own method?

2021-07-27 12:59 UTC, force2b commented on force-app/main/default/pages/CON_ContactMerge.page
> +                                        <th class="slds-text-heading_label" scope="col">{!$Label.commonContactCount}</th>
It looks like this page has a lot of hard-coded text (wow). Not that it all has to be fixed here, but can you open a new localization WI to fix the rest of the labels (if you haven't done that already)?

2021-07-27 14:08 UTC, dfuller114 requested changes
Looks good Reede! I've added a few comments regarding renaming abbreviated variables and methods. I think we should do as much of that for some of the legacy code in these classes as we can to clarify what the code is doing. I didn't add a comment for every occurrence, but I think we should at least remove abbreviations from method names and variables also if there's time. I've found the renaming Refactor feature in Illuminated Cloud to be really helpful for this.

2021-07-27 14:08 UTC, dfuller114 commented on force-app/main/default/classes/CON_ContactMerge_CTRL.cls
> +    private void getDRSFirstContacts(Set<Id> allDRIIds, List<DuplicateRecordItem> allDRIs) {
could we use duplicateRecordSet in the method name instead of abbreviation?

2021-07-27 18:50 UTC, npsp-reedestockton commented
@sam-knox Added another label on this one to replace a hard-coded field label - 'First Contact Name'

2021-07-27 18:54 UTC, npsp-reedestockton commented
@force2b @dfuller114 Code review suggestions have been implemented.  Thanks y'all!

2021-07-27 19:42 UTC, force2b approved these changes

2021-07-27 19:42 UTC, force2b commented on force-app/main/default/pages/CON_ContactMerge.page
> +                                        <th class="slds-text-heading_label" scope="col">{!$Label.commonContactCount}</th>
Labels very nicely handled!

2021-07-27 21:02 UTC, sam-knox commented
@npsp-reedestockton - Updated the title and change notes. Labels are good to go as they are!

2021-07-28 14:06 UTC, dfuller114 approved these changes
Looks good! Thanks Reede!

2021-07-30 01:52 UTC, merged