Updating Recurring Donation Change History to Recurring Donation Change Log
SalesforceFoundation/NPSP pull request #6655
Opened 2021-09-14 21:03 UTC by lparrott

- We updated all references of "Recurring Donation Change History" to "Recurring Donation Change Log" to better differentiate between out of the box Field History Tracking.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2021-09-16 17:57 UTC, bdvorachek commented on force-app/main/default/classes/RD2_ChangeLogSelector.cls
> +    public List<RecurringDonationChangeLog__c> getChangeHistories(Id recurringDonationId) {
Rename this to getChangeLogEntries?

2021-09-16 18:21 UTC, dfuller114 requested changes
looks good. added several comments to convert abbreviated method and variable names to more clear names where we can.

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService.cls
> +    private List<RecurringDonationChangeLog__c> changeLogList =
could we rename to `changeLogs`?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService.cls
>      public void handleHistoryFieldChanged(RD2_RecurringDonation updatedRd, RD2_RecurringDonation originalRd) {
rename to handleLogFieldChanged?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService.cls
> +            RecurringDonationChangeLog__c rdChangeLog = new RecurringDonationChangeLog__c(
rename to `changeLog` without "rd"?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService.cls
> +        public void insertChangeLogRecords(List<RecurringDonationChangeLog__c> changeLogList){
rename variable to `changeLogs`?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService_TEST.cls
> +        List<RecurringDonationChangeLog__c> rdclList = getRecurringDonationChangeLog(rd.Id);
rename to `changeLogs`?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService_TEST.cls
> +        List<RecurringDonationChangeLog__c> rdclList = getRecurringDonationChangeLog(rd.Id);
rename to `changeLogs`?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService_TEST.cls
> +        RecurringDonationChangeLog__c rdcl = rdclList[0];
rename to `changeLog`?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService_TEST.cls
> +        RD2_ChangeLogService rdclService = new RD2_ChangeLogService();
`changeLogService`?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_ChangeLogService_TEST.cls
> +        List<RecurringDonationChangeLog__c> rdclList = getRecurringDonationChangeLog(rd.Id);
`changeLogs`?

2021-09-16 18:21 UTC, dfuller114 commented on force-app/main/default/classes/RD2_OpportunityEvaluationService_TEST.cls
> +        RecurringDonationChangeLog__c rdcl = rdclList[0];
rename to `changeLog`?

2021-09-16 20:46 UTC, lparrott commented
@bdvorachek @dfuller114 Requested changes have been pushed, thanks for the thorough feedback!

2021-09-17 18:53 UTC, dfuller114 approved these changes
looks good! great work!

2021-09-17 19:03 UTC, bdvorachek approved these changes

2021-09-17 20:03 UTC, merged