Lead Conversion Error When User is Not Lead Owner In Private Account Sharing Model
SalesforceFoundation/NPSP pull request #6725
Opened 2021-10-31 17:24 UTC by dfuller114

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2021-11-01 15:31 UTC, dfuller114 commented on force-app/main/default/classes/LD_LeadConvertOverride_CTRL.cls
> +    public Boolean isLegacyAccount {
good callout. We actually use `LegacyHousehold` in our domain so I pushed a change to update this getter.

2021-11-02 16:21 UTC, lparrott commented on force-app/main/default/classes/LD_LeadConvertOverride_TEST.cls
> +    static void newLeadConversion_UserDoesNotOwnLeadRecord() {
Still a TODO?

2021-11-02 20:00 UTC, andrewyu-salesforce requested changes

2021-11-02 21:35 UTC, dfuller114 commented on force-app/main/default/classes/LD_LeadConvertOverride_CTRL.cls
> +    }
@andrewyu-salesforce good callout. just pushed an update. let me know what you think

2021-11-02 23:00 UTC, andrewyu-salesforce approved these changes
@dfuller114 everything looks great. Nice refactor

2021-11-03 15:33 UTC, lparrott approved these changes

2021-11-04 19:50 UTC, lparrott commented on force-app/main/default/classes/LD_LeadConvertOverride_CTRL.cls
> +    private with sharing class DMLWithoutSharing {
Should this be `without sharing`?

2021-11-04 19:50 UTC, lparrott commented on force-app/main/default/classes/LD_LeadConvertOverride_CTRL.cls
> +    private with sharing class AffiliationNonDupeWithoutSharing {
Should this be `without sharing`?

2021-11-04 23:16 UTC, andrewyu-salesforce approved these changes
great unit test on the user permission

2021-11-04 23:34 UTC, merged