Feature/callen/238  fix duplicate oppts when creating r dwith campaign
SalesforceFoundation/NPSP pull request #6761
Opened 2021-12-02 23:49 UTC by callen-sfdo

This fixes an issue where if a Recurring Donation is created in BDI with a campaign defined, but no initial Donation defined it still creates an initial donation.  This was occurring because the code that checks to see if any Opportunity Object mapping fields were populated was including the DonationCampaignImported__c field (Which is used by both RD and Oppts) in the populated field check that determines whether or not the Opportunity attempts to be created.

We are creating a field mapping because Donation Campaign Source was missed when we originally converted the help text mappings to the custom metadata "advanced" mappings.  It has been getting created automatically during advanced mapping enablement so it hasn't directly caused problems, but the fact that it is missing meant that the unit tests for Recurring Donation didn't catch this bug earlier. Adding it means that the default mapping is more accurate and we can now catch regressions for this bug.  It does not need to be added to any install scripts because an equivalent mapping has already been created for all orgs during enablement.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2021-12-03 00:16 UTC, grivero reviewed
Changes looks good overall but shouldn't we have unit tests to go over the changes in BDI_Donations and BDI_RecurringDonations?

2021-12-06 22:39 UTC, psadie-sfdo requested changes
One small request and I think this branch needs to be renamed to something like `feature/238__callenFixDuplicateOpptsWhenCreatingRDwithCampaign`

2021-12-08 00:22 UTC, psadie-sfdo requested changes

2021-12-08 00:22 UTC, psadie-sfdo commented on force-app/main/default/classes/BDI_DataImportService.cls
> +            Boolean shouldAddPopulatedField = !fieldsToIgnore.contains(diField.toLowerCase()) && di.get(diField) != null
Sorry, previous suggestion didn't have the closing ;
```suggestion
            Boolean shouldAddPopulatedField = !fieldsToIgnore.contains(diField.toLowerCase()) && di.get(diField) != null;
```

2021-12-10 21:49 UTC, closed without merging

2021-12-10 22:40 UTC, callen-sfdo commented
Changed branch name and opened new PR: https://github.com/SalesforceFoundation/NPSP/pull/6768