W-9871891: Learn More link does not warn it opens in new window
SalesforceFoundation/NPSP pull request #6788
Opened 2021-12-29 12:57 UTC by JoseRossiSF

# Work Item
[W-9871891](https://gus.lightning.force.com/a07EE000005MMYaYAO)

# Changes
Added aria-label attribute to Learn More link in gsApplicationStatus component so it warns users of screen readers that said link opens in a new tab.

2022-01-05 18:37 UTC, psadie-sfdo requested changes

2022-01-05 20:17 UTC, bdvorachek approved these changes

2022-01-05 21:55 UTC, psadie-sfdo approved these changes

2022-01-05 21:57 UTC, psadie-sfdo commented
Note: Feature - Prerelease failure should be resolved once this branch is caught up to feature/238 (this change specifically https://github.com/SalesforceFoundation/NPSP/pull/6786/files).

2022-01-06 13:51 UTC, mcasco approved these changes
lgtm

2022-01-07 12:03 UTC, merged