RD2: Sustainer Evaluation
SalesforceFoundation/NPSP pull request #6830
Opened 2022-01-31 23:37 UTC by andrewyu-salesforce

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2022-01-31 23:38 UTC, andrewyu-salesforce commented on force-app/main/default/objects/Account/fields/Sustainer__c.field-meta.xml
> +    <description>Determine if the Account is a sustainer</description>
@sam-knox Can you provide the description for Account/Contact Sustainer field?

2022-02-01 17:45 UTC, sam-knox commented on force-app/main/default/objects/Account/fields/Sustainer__c.field-meta.xml
> +    <description>Determine if the Account is a sustainer</description>
```suggestion
    <description>Indicates if this Account is an active, lapsed, or former recurring donor. The value is based on the Status of the related Recurring Donations.</description>
```

2022-02-01 17:46 UTC, sam-knox commented on force-app/main/default/objects/Account/fields/Sustainer__c.field-meta.xml
> +    <inlineHelpText>Determine if the Account is a sustainer</inlineHelpText>
```suggestion
    <inlineHelpText>Indicates if this Account is an active, lapsed, or former recurring donor. The value is based on the Status of the related Recurring Donations.</inlineHelpText>
```

2022-02-01 17:46 UTC, sam-knox commented on force-app/main/default/objects/Contact/fields/Sustainer__c.field-meta.xml
> +    <description>Determine if the Contact is a sustainer</description>
```suggestion
    <description>Indicates if this Contact is an active, lapsed, or former recurring donor. The value is based on the Status of the related Recurring Donations.</description>
```

2022-02-01 17:47 UTC, sam-knox commented on force-app/main/default/objects/Contact/fields/Sustainer__c.field-meta.xml
> +    <inlineHelpText>Determine if the Contact is a sustainer</inlineHelpText>
```suggestion
    <inlineHelpText>Indicates if this Contact is an active, lapsed, or former recurring donor. The value is based on the Status of the related Recurring Donations.</inlineHelpText>
```

2022-02-01 17:47 UTC, sam-knox requested changes
Ok, I just added the description and help text for these fields.

2022-02-09 21:32 UTC, closed without merging