Adding a new CCI flow for configuring the TSO org
SalesforceFoundation/NPSP pull request #6869
Opened 2022-03-01 17:28 UTC by lparrott

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2022-03-02 02:08 UTC, bdvorachek approved these changes
When we change this out to use the beta package, make sure we get the template id out of orgs/trial.json.

2022-03-02 22:19 UTC, dfuller114 commented on cumulusci.yml
> +                flow: enable_rd2_managed
@lparrott I think we can just use `enable_rd2` here. I ran it against a managed org and it went through fine. It doesn't appear that the `managed` property is needed to warrant a separate flow for this. If we could just use `enable_rd2` that would help avoid confusion around why that flow has a `managed` suffix and the others don't.

2022-03-02 23:34 UTC, dfuller114 requested changes
@lparrott I think we can just use enable_rd2 here. I ran it against a managed org and it went through fine. It doesn't appear that the managed property is needed to warrant a separate flow for this. If we could just use enable_rd2 that would help avoid confusion around why that flow has a managed suffix and the others don't.

2022-03-10 15:39 UTC, dfuller114 approved these changes

2022-03-16 15:08 UTC, dfuller114 commented
@lparrott not sure why, but you disappeared from the review and i don't seem to be able to add you again.

2022-03-17 20:30 UTC, bdvorachek commented on unpackaged/config/trial/standardValueSetTranslations/ContactRole-de.standardValueSetTranslation
> +<StandardValueSetTranslation xmlns="http://soap.sforce.com/2006/04/metadata">
Maybe these standardValueSetTranslations should live in the trial_translations folder? There's some duplicated metadata between the two.

2022-03-18 20:36 UTC, andrewyu-salesforce reviewed
@dfuller114 minor feedback on the description of the `enable_rd2` flow

2022-03-18 20:36 UTC, andrewyu-salesforce commented on cumulusci.yml
> -    enable_rd2_managed:
The description (line 1008)for `enable_rd2` flow should be modified to indicate it works for both managed and un-managed code.

2022-03-18 20:38 UTC, andrewyu-salesforce approved these changes

2022-03-18 21:25 UTC, lparrott commented
Approved! (Since this started as my PR, I can't actually approve it 😉)

2022-03-21 15:00 UTC, merged