[W-10501541] - Fix payment method bug
SalesforceFoundation/NPSP pull request #6891
Opened 2022-03-18 13:12 UTC by JoseRossiSF

# Work Item
[W-10501541](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000jE366YAC/view)

# Changes
Now, the payment method of the payment is displayed regardless of the Paid checkbox field.
Only when an opportunity has multiple payments the condition to list a Payment Method should be the value of the earliest payment record marked as Paid.

2022-03-18 17:17 UTC, dcaballeroSf requested changes
Some comments to work on. Specially in DonationHistoryService

2022-03-18 17:17 UTC, dcaballeroSf commented on force-app/main/service/DonationHistoryService.cls
> +            paymentMethodToReturn =  paymentListForOpportunity.get(0).npe01__Payment_Method__c;
I think this approach is better, your code has some potential problems(you ask if size > 1 but then you use the first element assuming is there, which is something you cannot warranty; you have multiple if and else and there is some indentation problems)

```
paymentMethodToReturn = ''
for (npe01__OppPayment__c p : paymentListForOpportunity) {
    if (paymentMethodToReturn == '') {
        paymentMethodToReturn = p.npe01__Payment_Method__c;
        continue;
    }
   if(p.npe01__Paid__c){
        paymentMethodToReturn = p.npe01__Payment_Method__c;
        break;
    }
}
return paymentMethodToReturn;
```

2022-03-21 20:42 UTC, dcaballeroSf commented on force-app/main/service/DonationHistoryService.cls
> +		for (npe01__OppPayment__c p : paymentListForOpportunity) {
We still have a indentation issue here. Configure VSCode to indent with 4 spaces instead of tabulation

2022-03-22 16:07 UTC, dcaballeroSf approved these changes
Besides a spacing issue, LGTM. Just make it sure you fix it before merging

2022-03-22 18:01 UTC, maurimart approved these changes
LGTM

2022-03-22 19:09 UTC, lparrott reviewed
Looks good, just had some minor comments.

2022-03-22 19:09 UTC, lparrott commented on force-app/main/service/DonationHistoryService.cls
> +    * @return String with payment method for current opportunity
Technically it returns the Payment Method for the first Paid Payment, unless none are paid, then it returns the first Payment's Payment Method, right? Let's update this!

2022-03-23 14:52 UTC, lparrott commented
@JoseRossiSF I'm receiving a 500 error when trying to approve, so consider this message my approval! 👍

2022-03-25 19:37 UTC, merged