W-11552158 - Adding 'Failing' as Recurring Donation Status
SalesforceFoundation/NPSP pull request #7130
Opened 2022-10-17 23:38 UTC by callen-sfdo

- Added 'Failing' to the Status Picklist
- Added mapping for 'Failing' to 'Active' in the RD Status Mapper

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2022-10-18 19:13 UTC, andrewyu-salesforce approved these changes

2022-10-19 16:09 UTC, lparrott approved these changes

2022-10-20 17:19 UTC, andrewyu-salesforce commented
@callen-sfdo After testing the PR and creating the test suite, I noticed a couple of things that need to be changed:
1. Failing Status default mapping should be added to `RD2_StatusMApper_TEST.getDefaultStatusLabelByValue()` so it can be tested in the unit test
2. The Status should be added to the `rd2_post_config` file instead of where it is currently added because we don't want the field to show up in RD1.

2022-10-20 17:24 UTC, andrewyu-salesforce requested changes
See comment aboved

2022-10-24 15:58 UTC, andrewyu-salesforce approved these changes

2022-10-24 15:58 UTC, merged