Updating yml with static release notes
SalesforceFoundation/NPSP pull request #7173
Opened 2023-03-14 17:42 UTC by lparrott

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2023-03-15 14:48 UTC, melissabarber approved these changes
@lparrott Thank you for making this update so quickly! I added a suggestion with the CX-approved text that I just got back from the reviewer.

2023-03-15 14:48 UTC, melissabarber commented on cumulusci.yml
> +                [Salesforce.org Release Notes](https://help.salesforce.com/s/articleView?id=sfdo.Release_Notes_SFDO.htm&type=5)
```suggestion
                Check out the Salesforce Release Notes on [Salesforce Help & Training](https://sfdc.co/bnL4Cb).
```

2023-03-15 16:21 UTC, jstvz requested changes
±: Since the option was just added we need to update the `minimum_cumulusci_version` to 3.74.0.

This will break your builds until we get MetaCI updated, however.

2023-03-16 22:03 UTC, jstvz approved these changes

2023-07-06 22:04 UTC, merged