a11y WCAG 2.1 color contrast updates
SalesforceFoundation/NPSP pull request #7190
Opened 2023-09-07 22:10 UTC by npsp-reedestockton

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2023-09-07 22:13 UTC, npsp-reedestockton commented
[W-9537095](https://gus.lightning.force.com/lightning/r/a07AH000000PxQJYA0/view)
[W-9537133](https://gus.lightning.force.com/lightning/r/a07AH000000PxT8YAK/view)
[W-9537117](https://gus.lightning.force.com/lightning/r/a07AH000000PxS0YAK/view)
[W-14001172](https://gus.lightning.force.com/lightning/r/a07EE00001Z8t04YAB/view)

2023-09-08 13:55 UTC, lparrott requested changes
Great work! The bulk of my testing will be spent on the checkbox changes, just because there's a small risk of regression there. I'll approve after testing.

2023-09-08 13:55 UTC, lparrott commented on force-app/main/default/pages/MTCH_FindGifts.page
> +                                <div class="slds-form-element__control">
Great solution!

2023-09-08 13:55 UTC, lparrott commented on force-app/main/default/pages/STG_PanelContactRoles.page
> +                    </label>                                        <apex:outputPanel id="cbxARPCHelp" layout="block">
Missing a new line here? Looks like there's a few of these, I'll let you find/fix the rest 😉

2023-09-08 13:55 UTC, lparrott commented on force-app/main/default/pages/STG_PanelAllocations.page
> +                        </label>                        <apex:outputPanel id="cbxUFYFRHelp" layout="block">
Missing new line?

2023-09-08 13:55 UTC, lparrott commented on force-app/main/default/pages/STG_PanelTDTM.page
> -                            <apex:inputField value="{!thNew.Class__c}" required="false" id="tbxC" html-aria-describedby="{!$Component.tbxCHelp}" styleClass="fslds-input"
I think we both know what the "f" stands for

2023-09-08 16:56 UTC, lparrott approved these changes

2023-09-08 17:50 UTC, merged