Commit -- BDI_DataImport_BATCH is queued on GE Processor Queue
SalesforceFoundation/NPSP pull request #7232
Opened 2024-03-29 08:44 UTC by enzigma-pratishtha-upadhyay

Executing the BDI_DataImport_BATCH batch on GiftEntryProcessorQueue to update  the NPSP Data Import batch record fields.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

2024-04-09 16:57 UTC, daniel-fuller requested changes
@enzigma-pratishtha-upadhyay In the Feature Test and 2gp Feature Test autobuilds there are failing apex tests that need to be fixed in order to ensure that we haven't created a regression here with this change. Please fix the failing tests in those builds and I will re-review. Thanks.

2024-05-13 15:41 UTC, daniel-fuller commented
I've completed QA on this successfully and the fix is working

2024-05-13 15:47 UTC, daniel-fuller approved these changes

2024-05-13 19:00 UTC, callen-sfdo approved these changes

2024-05-14 14:38 UTC, lparrott approved these changes
Nice work!

2024-05-14 14:38 UTC, merged